<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Users control</title>
        <link rel="stylesheet" href="css/bootstrap.css">
                <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>
<!--         <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>-->
               <script type="text/javascript" src="js/bootstrap.js"></script>
<!--        <script type="text/javascript" src="js/npm.js"></script>-->
    </head>
    <nav class="navbar navbar-default">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="index.php">Users control</a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="active"><a href="index.php">Home</a></li>
                <li><a href="index.php?c=controller&a=listadoUsuarios2&; ?">Usuarios</a></li>
                <li><a href="index.php?c=controller&a=listadoEquipos&; ?">Equipos</a></li>
                <li><a href="index.php">Cerrar sesion</a></li>
<!--                <li><a href="index.php?c=controller&a=listadoUsuarios2&; ?">Impresoras</a></li>-->
            </ul>
        </div>
    </nav>
    <body>